In [28]:
#Problem 1

#Initialize an empty array with size 2*2
import numpy as np
array = np.empty((2,2))
print(array)

[[23. 51.]
 [13. 29.]]


In [2]:
#initialize an all one array with size 4*2
import numpy as np
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:

import numpy as np#Return a new array of given shape and type, filled with filll_value.
filled_arr = np.full((2,2),4)
print(filled_arr)

[[4 4]
 [4 4]]


In [4]:
#Return a new array of zeros with same shape and type as given array.
import numpy as np
arr = np.array([[7,2,3],[4,9,6]])
zeros_array = np.zeros_like(arr)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [5]:
#Return a new array of ones with same shape and type as given array.
import numpy as np
arr = np.array([[7,2,3],[4,9,6]])
ones_array = np.ones_like(arr)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [6]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.
import numpy as np
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [7]:
#Problem 2

#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
import numpy as np
arr = np.arange(9)
array = arr.reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Create a random array of size 30 and find the mean of the array.
import numpy as np
random_array = np.random.random(30)
mean = random_array.mean()
print("The random array of size 30 is: ",random_array)
print("\nThe mean of the random array is: ",mean)

The random array of size 30 is:  [0.49935012 0.60397447 0.45974486 0.01608384 0.14319693 0.05518622
 0.07286487 0.41092937 0.54495238 0.8011896  0.49372261 0.29549147
 0.3333588  0.42826258 0.61673446 0.86548    0.3391366  0.541968
 0.02763057 0.77430402 0.44502972 0.26968692 0.33410236 0.63876482
 0.03217866 0.94238741 0.9350303  0.61894685 0.7951828  0.67072827]

The mean of the random array is:  0.46685332983358824


In [11]:
#Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np
random_arr = np.random.random((10,10))
print("The maximum value of random arry is: ",random_arr.max())
print("The minimum value of random array is: ",random_arr.min())

The maximum value of random arry is:  0.9973223186693634
The minimum value of random array is:  0.00040506506054927005


In [12]:
#Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
array = np.zeros(10)
array[4]=1
print("Replaced arry: ",array)

Replaced arry:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#Reverse an array arr = [1,2,0,0,4,0].
import numpy as np
array = np.array([1,2,0,0,4,0])
reversed_array = array[::-1]
print("The reversed array is: ",reversed_array)

The reversed array is:  [0 4 0 0 2 1]


In [14]:
#Create a 2d array with 1 on border and 0 inside.
import numpy as np
array = np.ones((4,4))
array[1:-1, 1:-1] =0
print("The 2d array with 1 on border and 0 inside:\n", array)

The 2d array with 1 on border and 0 inside:
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [15]:
#Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np
array = np.zeros((8,8))
array[1::2, ::2] =1
array[::2, 1::2] = 1
print("The checkerboarder pattern array:\n", array)

The checkerboarder pattern array:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [16]:
#Problem 3

#For the following arrays: x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); v = np.array([9,10]) and w = np.array([11,12]);

#Add the two array.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
add = x+y
print("The addition of two array: \n ",add)

The addition of two array: 
  [[ 6  8]
 [10 13]]


In [17]:
#Subtract the two array
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
sub = x-y
print("The substraction of two array: \n ",sub)

The substraction of two array: 
  [[-4 -4]
 [-4 -3]]


In [18]:
#Multiply the array with any integers of your choice.
import numpy as np
x = np.array([[1,2],[3,5]])
mul = x*7
print("The multiplication of array with 7: \n",mul)

The multiplication of array with 7: 
 [[ 7 14]
 [21 35]]


In [19]:
#Find the square of each element of the array.
import numpy as np
x = np.array([[1,2],[3,5]])
square = x**2
print("The square of each element of array: \n",square)


The square of each element of array: 
 [[ 1  4]
 [ 9 25]]


In [20]:
#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("The dot product of v.w:", dot_vw)
print("The dot product of x.v:", dot_xv)
print("The dot product of x.y:\n", dot_xy)


The dot product of v.w: 219
The dot product of x.v: [29 77]
The dot product of x.y:
 [[19 22]
 [50 58]]


In [21]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
print("Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))
print("Concatenate v and w along column:\n", np.column_stack((v, w)))

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [22]:
#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
import numpy as np
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])
try:
    concat = np.concatenate((x, v), axis=0)
    print(concat)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [23]:
#Problem - 4

#• For the following arrays: A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]])

#Prove A.A-1 = I.

import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A_inverse = np.linalg.inv(A)
i = np.dot(A, A_inverse)
print("A · A⁻¹ =\n", i)

A · A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [24]:
#Prove AB ̸= BA.
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("A·B =\n", AB)
print("B·A =\n", BA)
print("A·B == B·A ?", np.allclose(AB, BA))

A·B =
 [[23 13]
 [51 29]]
B·A =
 [[36 44]
 [13 16]]
A·B == B·A ? False


In [25]:
#Prove (AB)^T =B^T*A^T
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)
print("(AB)ᵀ =\n", AB_T)
print("Bᵀ·Aᵀ =\n", B_T_A_T)
print("Are they equal?", np.allclose(AB_T, B_T_A_T))

(AB)ᵀ =
 [[23 51]
 [13 29]]
Bᵀ·Aᵀ =
 [[23 51]
 [13 29]]
Are they equal? True


In [26]:
#Solve the following system of Linear equation using Inverse Methods.

#2x − 3y + z = −1

#x − y + 2z = −3

#3x + y − z = 9
import numpy as np
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])
solution = np.dot(np.linalg.inv(coeff_matrix), constants)
print("Solution [x, y, z] =", solution)

Solution [x, y, z] = [ 2.  1. -2.]
